./mill custodial-copy-queue-creator.deploy
./mill entity-event-generator-lambda.deploy
./mill get-latest-preservica-version-lambda.deploy
./mill ingest-asset-opex-creator.deploy
./mill ingest-asset-reconciler.deploy
./mill ingest-failure-notifications.deploy
./mill ingest-files-change-handler.deploy
./mill ingest-find-existing-asset.deploy
./mill ingest-flow-control.deploy
./mill ingest-folder-opex-creator.deploy
./mill ingest-mapper.deploy
./mill ingest-parent-folder-opex-creator.deploy
./mill ingest-parsed-court-document-event-handler.deploy
./mill ingest-start-workflow.deploy
./mill ingest-upsert-archive-folders.deploy
./mill ingest-validate-generic-ingest-inputs.deploy
./mill ingest-workflow-monitor.deploy
./mill preingest-tdr-aggregator.deploy
./mill preingest-tdr-package-builder.deploy
./mill rotate-preservation-system-password.deploy
