import sbt._
object Dependencies {
  lazy val logbackVersion = "2.25.3"
  lazy val pureConfigVersion = "0.17.10"
  lazy val daAwsClientsVersion = "0.1.141"
  private val fs2Version = "3.13.0-M8"
  private val sttpVersion = "4.0.15"
  private val circeVersion = "0.15.0-M1"
  private val log4CatsVersion = "2.7.1"
  private val awsLibraryVersion = "1.12.797"
  private lazy val scalaTestVersion = "3.2.19"

  lazy val awsCrt = "software.amazon.awssdk.crt" % "aws-crt" % "0.43.4"
  lazy val awsLambda = "com.amazonaws" % "aws-java-sdk-lambda" % awsLibraryVersion
  lazy val catsEffect = "org.typelevel" %% "cats-effect" % "3.6.3"
  lazy val circeCore = "io.circe" %% "circe-core" % circeVersion
  lazy val circeGeneric = "io.circe" %% "circe-generic" % circeVersion
  lazy val circeParser = "io.circe" %% "circe-parser" % circeVersion
  lazy val circeFs2 = "io.circe" %% "circe-fs2" % "0.14.1"
  lazy val commonsCompress = "org.apache.commons" % "commons-compress" % "1.28.0"
  lazy val commonsLogging = "commons-logging" % "commons-logging" % "1.3.5"
  lazy val commonsLang = "org.apache.commons" % "commons-lang3" % "3.20.0"
  lazy val awsDynamo = "software.amazon.awssdk" % "dynamodb" % "2.41.34"
  lazy val dynamoClient = "uk.gov.nationalarchives" %% "da-dynamodb-client" % daAwsClientsVersion
  lazy val eventBridgeClient = "uk.gov.nationalarchives" %% "da-eventbridge-client" % daAwsClientsVersion
  lazy val fs2Core = "co.fs2" %% "fs2-core" % fs2Version
  lazy val fs2IO = "co.fs2" %% "fs2-io" % fs2Version
  lazy val fs2Reactive = "co.fs2" %% "fs2-reactive-streams" % fs2Version
  lazy val jawnFs2 = "org.typelevel" %% "jawn-fs2" % "2.5.0-RC1"
  lazy val jawnParser = "org.typelevel" %% "jawn-parser" % "1.6.0"
  lazy val jaxb = "javax.xml.bind" % "jaxb-api" % "2.3.1"
  lazy val jsonSchemaValidator = "com.networknt" % "json-schema-validator" % "3.0.0"
  lazy val lambdaCore = "com.amazonaws" % "aws-lambda-java-core" % "1.4.0"
  lazy val lambdaJavaEvents = "com.amazonaws" % "aws-lambda-java-events" % "3.16.1"
  lazy val log4CatsCore = "org.typelevel" %% "log4cats-core" % log4CatsVersion
  lazy val log4CatsSlf4j = "org.typelevel" %% "log4cats-slf4j" % log4CatsVersion
  lazy val log4jCore = "org.apache.logging.log4j" % "log4j-core" % logbackVersion
  lazy val log4jSlf4j = "org.apache.logging.log4j" % "log4j-slf4j-impl" % logbackVersion
  lazy val log4jTemplateJson = "org.apache.logging.log4j" % "log4j-layout-template-json" % logbackVersion
  lazy val mockito = "org.scalatestplus" %% "mockito-5-10" % "3.2.18.0"
  lazy val preservicaClient = "uk.gov.nationalarchives" %% "preservica-client-fs2" % "0.0.158"
  lazy val pureConfigCats = "com.github.pureconfig" %% "pureconfig-cats-effect" % pureConfigVersion
  lazy val pureConfig = "com.github.pureconfig" %% "pureconfig-core" % pureConfigVersion
  lazy val reactorTest = "io.projectreactor" % "reactor-test" % "3.8.3"
  lazy val scalaCheck = "org.scalacheck" %% "scalacheck" % "1.19.0"
  lazy val scalaCheckPlus = "org.scalatestplus" %% "scalacheck-1-16" % "3.2.14.0"
  lazy val scanamo = "org.scanamo" %% "scanamo" % "6.0.0"
  lazy val s3Client = "uk.gov.nationalarchives" %% "da-s3-client" % daAwsClientsVersion
  lazy val sqsClient = "uk.gov.nationalarchives" %% "da-sqs-client" % daAwsClientsVersion
  lazy val scalaParserCombinators = "org.scala-lang.modules" %% "scala-parser-combinators" % "2.4.0"
  lazy val scalaTest = "org.scalatest" %% "scalatest" % scalaTestVersion
  lazy val scalaXml = "org.scala-lang.modules" %% "scala-xml" % "2.4.0"
  lazy val sfnClient = "uk.gov.nationalarchives" %% "da-sfn-client" % daAwsClientsVersion
  lazy val ssmClient = "uk.gov.nationalarchives" %% "da-ssm-client" % daAwsClientsVersion
  lazy val snsClient = "uk.gov.nationalarchives" %% "da-sns-client" % daAwsClientsVersion
  lazy val secretsManagerClient = "uk.gov.nationalarchives" %% "da-secretsmanager-client" % daAwsClientsVersion
  lazy val sttpClient = "com.softwaremill.sttp.client4" %% "core" % sttpVersion
  lazy val sttpClientFs2 = "com.softwaremill.sttp.client4" %% "fs2" % sttpVersion
  lazy val sttpCirce = "com.softwaremill.sttp.client4" %% "circe" % sttpVersion
  lazy val typeSafeConfig = "com.typesafe" % "config" % "1.4.5"
  lazy val upickle = "com.lihaoyi" %% "upickle" % "4.4.2"
  lazy val wiremock = "org.wiremock" % "wiremock" % "3.13.2"
}
