name: DR2 Build Project
on:
  push:
    branches:
      - main
    paths:
      - scala/lambdas/**
      - python/lambdas/**
      - build.sbt
permissions:
  id-token: write
  contents: write
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    outputs:
      next-version: ${{ steps.next-tag.outputs.next-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials from management account
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/MgmtDPGithubCodeDeploy
          aws-region: eu-west-2
          role-session-name: GitHubActionsRole
      - id: next-tag
        uses: nationalarchives/dr2-github-actions/.github/actions/get-next-version@main
        with:
          repo-name: dr2-ingest
      - run: |
          rm -rf target/outputs
          mkdir -p target/outputs
          sbt ingestLambdasRoot/assembly
          zip -jA copy-files-from-tdr python/lambdas/copy-files-from-tdr/lambda_function.py
          zip -jA ingest-cc-notifications python/lambdas/ingest-cc-notifications/cc_notifications/lambda_function.py
          cp copy-files-from-tdr target/outputs/
          cd target/outputs
          aws s3 sync . s3://mgmt-dp-code-deploy/${{ steps.next-tag.outputs.next-version }}/
          git tag ${{ steps.next-tag.outputs.next-version }}
          git push origin ${{ steps.next-tag.outputs.next-version }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=${{ needs.pre-deploy.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
