name: DR2 Build Project
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    outputs:
      next-version: ${{ steps.next-tag.outputs.next-version }}
    steps:
      - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      - uses: sbt/setup-sbt@1202a759c4b688938a614ac91771ba6ab7686f0a
      - name: Configure AWS credentials from management account
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/MgmtDPGithubCodeDeploy
          aws-region: eu-west-2
          role-session-name: GitHubActionsRole
      - id: next-tag
        uses: nationalarchives/dr2-github-actions/.github/actions/get-next-version@917201e254f112ff041b952dae76ef767cae7378
        with:
          repo-name: dr2-ingest
      - run: |
          rm -rf target/outputs
          mkdir -p target/outputs
          sbt ingestLambdasRoot/assembly
          (cd ./python/lambdas/preingest-importer/ && bash deploy.sh)
          zip -jA preingest-tdr-importer python/lambdas/preingest-importer/lambda_function.py
          cp preingest-tdr-importer target/outputs
          cp preingest-tdr-importer target/outputs/preingest-dri-importer
          cd target/outputs
          aws s3 sync . s3://mgmt-dp-code-deploy/${{ steps.next-tag.outputs.next-version }}/
          git tag ${{ steps.next-tag.outputs.next-version }}
          git push origin ${{ steps.next-tag.outputs.next-version }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=${{ needs.pre-deploy.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
