name: DR2 Build Project
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
jobs:
  setup-tests:
    runs-on: ubuntu-latest
    outputs:
      next-version: ${{ steps.next-tag.outputs.next-version }}
      projects: ${{ steps.generate-files.outputs.projects }}
    steps:
      - uses: actions/checkout@v3
      - id: generate-files
        run: |
          echo $(sbt -warn printProjectsTask)
          PROJECTS=$(sbt -warn printProjectsTask | jq)
          echo ${PROJECTS}
          echo projects=${PROJECTS} >> $GITHUB_OUTPUT
      - run: pip install requests
      - id: next-tag
        uses: nationalarchives/dr2-github-actions/.github/actions/get-next-version@main
        with:
          repo-name: dr2-ingest
  pre-deploy:
    needs: setup-tests
    strategy:
      matrix:
        projects: ${{ fromJSON(needs.setup-tests.outputs.projects) }}
    runs-on: ubuntu-latest
    steps:
      - run: | 
          sbt ${{ matrix.projects.project }}/assembly
          aws s3 cp ${{ matrix.projects.path }}/target/scala-2.13/${{ matrix.projects.path }}.jar s3://mgmt-dp-code-deploy/${{ steps.next-tag.outputs.next-version }}/${{ matrix.projects.path }}.jar
