name: DR2 Build Project
on:
  push:
    branches:
      - main
    paths-ignore: ["docs/**"]
permissions:
  id-token: write
  contents: write
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    outputs:
      next-version: ${{ steps.next-tag.outputs.next-version }}
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: sbt/setup-sbt@3e125ece5c3e5248e18da9ed8d2cce3d335ec8dd
      - name: Configure AWS credentials from management account
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/MgmtDPGithubCodeDeploy
          aws-region: eu-west-2
          role-session-name: GitHubActionsRole
      - id: next-tag
        uses: nationalarchives/dr2-github-actions/.github/actions/get-next-version@917201e254f112ff041b952dae76ef767cae7378
        with:
          repo-name: dr2-ingest
      - run: |
          rm -rf target/outputs
          mkdir -p target/outputs
          sbt ingestLambdasRoot/assembly
          (cd ./python/lambdas/preingest-importer/ && bash deploy.sh)
          zip -jA preingest-tdr-importer python/lambdas/preingest-importer/lambda_function.py
          cp preingest-tdr-importer target/outputs
          cp preingest-tdr-importer target/outputs/preingest-dri-importer
          zip -jA ingest-metric-collector python/lambdas/ingest-metric-collector/ingest_metric_collector.py
          zip -jA pause-ingest python/lambdas/pause-ingest/pause_ingest.py
          zip -jA pause-preservica-activity python/lambdas/pause-preservica-activity/pause_preservica_activity.py
          cp ingest-metric-collector target/outputs
          cp pause-ingest target/outputs
          cp pause-preservica-activity target/outputs
          cd target/outputs
          aws s3 sync . s3://mgmt-dp-code-deploy/${{ steps.next-tag.outputs.next-version }}/
          git tag ${{ steps.next-tag.outputs.next-version }}
          git push origin ${{ steps.next-tag.outputs.next-version }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=${{ needs.pre-deploy.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
