name: Run DR2 Ingest End-to-End Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - intg
          - staging
        description: The environment to run the tests for
      to-deploy:
        type: string
        description: The version to deploy. Used to trigger a deploy in the next environment
permissions:
  id-token: write
  contents: write
env:
  TO_DEPLOY: ${{ github.event.inputs.to-deploy }}
jobs:
  run_tests:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: sbt/setup-sbt@508b753e53cb6095967669e0911487d2b9bc9f41 # v1.1.22
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-duration-seconds: 7200
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/${{ github.event.inputs.environment }}-dr2-run-e2e-tests-role
          aws-region: eu-west-2
          role-session-name: RunE2ETestsRole
      - run: |
          cd kotlin/e2e-tests/e2etests/
          gradle test
        env:
          INGEST_SQS_QUEUE: https://sqs.eu-west-2.amazonaws.com/${{ secrets.ACCOUNT_NUMBER }}/${{ github.event.inputs.environment }}-dr2-preingest-tdr-importer
          EXTERNAL_LOG_GROUP: arn:aws:logs:eu-west-2:${{ secrets.ACCOUNT_NUMBER }}:log-group:/${{ github.event.inputs.environment }}-external-notifications
          PREINGEST_SFN_ARN: arn:aws:states:eu-west-2:${{ secrets.ACCOUNT_NUMBER }}:stateMachine:${{ github.event.inputs.environment }}-dr2-preingest-tdr
          COPY_FILES_LOG_GROUP: arn:aws:logs:eu-west-2:${{ secrets.ACCOUNT_NUMBER }}:log-group:/aws/lambda/${{ github.event.inputs.environment }}-dr2-preingest-tdr-importer
          JUDGMENT_SQS_QUEUE: https://sqs.eu-west-2.amazonaws.com/${{ secrets.ACCOUNT_NUMBER }}/${{ github.event.inputs.environment }}-dr2-preingest-courtdoc-importer
          S3_BUCKET: ${{ github.event.inputs.environment }}-dr2-ingest-raw-cache
          LOCK_TABLE: ${{ github.event.inputs.environment }}-dr2-ingest-lock
      - run: gh workflow run deploy.yml -f environment=staging -f to-deploy=$TO_DEPLOY
        if: ${{ github.event.inputs.environment == 'intg' }}
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - run: gh workflow run deploy.yml -f environment=prod -f to-deploy=$TO_DEPLOY
        if: ${{ github.event.inputs.environment == 'staging' }}
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
