name: Disable NAT gateways overnight
on:
  workflow_dispatch:
    inputs:
      enabled:
        required: true
        type: boolean

permissions: {}

jobs:
  apply:
    strategy:
      matrix:
        environment: [intg]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@6782cb1b6df5d32e9354c1e6d6da4f956c0d61c4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/${{ matrix.environment == 'intg' && 'IntgTerraformRole' || 'StagingTerraformRole' }}
          aws-region: eu-west-2

      - if: inputs.enabled == false
        run: |
          aws lambda invoke --function-name ${{ matrix.environment }}-dr2-pause-ingest --payload '{"pause": true}' response.json

      - uses: hashicorp/setup-terraform@b75000b53e9ce4de2b4712237bbdb711bdc92aba

      - working-directory: terraform
        run: |
          terraform init
          export TF_VAR_lambda_code_version=$(curl  https://api.github.com/repos/nationalarchives/dr2-ingest/tags | jq -r '.[0].name')
          terraform workspace select ${{ matrix.environment }}
          if [ "${{ inputs.enabled }}" = "false" ]; then
            terraform apply -auto-approve \
                -var="use_nat_gateway=false" \
                -var="use_nat_instance=false" \
                -var="interface_endpoints={}"
            else
                terraform apply -auto-approve
            fi

      -  if: inputs.enabled == true
         run: |
           aws lambda invoke --function-name ${{ matrix.environment }}-dr2-pause-ingest --payload '{"pause": false}' response.json