name: DR2 Run Lambda Tests
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/README.md"
permissions:
  id-token: write
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
      - uses: scalacenter/sbt-dependency-submission@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3.2.3
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      - run: |
          curl -Lo wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64
          curl -Lo /tmp/wizcli-sha256 https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64-sha256
          curl -Lo /tmp/wizcli-sha256.sig https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64-sha256.sig
          chmod +x wizcli
          curl -Lo public_key.asc https://downloads.wiz.io/wizcli/public_key.asc
          gpg --import public_key.asc
          gpg --verify /tmp/wizcli-sha256.sig /tmp/wizcli-sha256
          echo "$(cat /tmp/wizcli-sha256) wizcli" | sha256sum --check
          ./wizcli scan dir .
          (cd terraform && terraform fmt -check --recursive)
          find . -name requirements.txt | xargs -I {} pip install -r {}
          pytest
          (cd rust/lambdas/courtdoc-anonymiser && cargo fmt --check && cargo test --workspace)
          sbt scalafmtCheckAll test
          (cd kotlin/e2e-tests/lib && gradle test)
        env:
          AWS_DEFAULT_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
